# Sentinel 0.0.2
# ____                   __                        ___
#/\  _`\                /\ \__  __                /\_ \
#\ \,\L\_\     __    ___\ \ ,_\/\_\    ___      __\//\ \
# \/_\__ \   /'__`\/' _ `\ \ \/\/\ \ /' _ `\  /'__`\\ \ \
#   /\ \L\ \/\  __//\ \/\ \ \ \_\ \ \/\ \/\ \/\  __/ \_\ \_
#   \ `\____\ \____\ \_\ \_\ \__\\ \_\ \_\ \_\ \____\/\____\
#    \/_____/\/____/\/_/\/_/\/__/ \/_/\/_/\/_/\/____/\/____/
#     ]======------ Configuration & Setup Guide ------=====[
#            Sentinel is inspired by WickBot.com
#        Be sure to check out their amazing discord bot!
config :
  plugin:
    # --------------------------------
    # Anti-Nuke Setup (Do this first)
    # --------------------------------
    prefix: "§d§lSentinel §8» §7" # Prefix of the plugin. Line below is the discord webhook for logs to be sent to
    webhook: "https://discord.com/api/webhooks/1124908469842096211/7NGOeFvtmxQ4n0_hSvbqhZUjnzRHIicLpHKETYU92n9JaLUPPsueBSn7w4wUfAnhjlLF"
    trusted: # List the UUIDs of players who are trusted, will bypass the plugin and be immune to logs and are able to re-op themeselves
      - "049460f7-21cb-42f5-8059-d42752bf406f" # obvWolf
    block-specific: true # Defaulted true | Weather or not to block ALL plugin specific commands from non-trusted members (EX: minecraft:ban) these will not be logged.
    prevent-nbt: true # Defaulted true | Should NBT items be blocked from the creative hotbar
    prevent-cmdblocks: true # Defaulted true | Should all command  block actions be blocked
    dangerous: # These commands can only be run by "trusted" users
      - "op"
      - "deop"
      - "stop"
      - "execute"
      - "sudo"
    log-dangerous: true # Default true | Weather or not to log when a dangerous command is executed
    log-cmdblocks: true # Defaulted true | Log attempts of command-block place-ery
    log-nbt: true # Defaulted true | Should items and their NBT's be logged
    logged: # Commands that will always be logged when executed.
      - "gamemode"
      - "give"
    deop: true # Defaulted true | This will remove an untrusted player's operator permissions whenever they attempt dangerous actions
    ban: false
    nbt-punish: false # Defaulted false | This will ban a player when they attempt to use an NBT item
    cmdblock-punish: false # Defaulted false | This will ban a player when they attempt to use a command block
    command-punish: true # Defaulted true | This will ban a player when they attempt to use a dangerous command
    reop-command: false # Defaulted false | This enables the command allowing trusted players to op themselves if they get deoped.
    # -------------------------------
    # Chat Filter Setup & AntiSpam
    # -------------------------------
  chat:
    anti-unicode: true # Default true | Prevents all non A-Z 0-9 + specials from being sent in chat
    anti-spam:
      # AntiSpam Heat system
      enabled: true # Default true | Enables/disables the entire anti-spam
      default-gain: 1 # Default 1 | Heat gained as base for every message
      low-gain: 2 # Default 2 | Heat gained when message is >25% similar
      medium-gain: 4 # Default 4 | Heat gained when message is >50% similar
      high-gain: 6 # Default 6 | Heat gained for >90% similarity
      heat-decay: 1 # Default 1 | Heat lost every second
      block-heat: 10 # Default 10 | The heat required to block the message
      punish-heat: 15 # Default 15 | The heat required to punish the player
      punish-command: "mute %player% 1m Please refrain from spamming!" # (Use %player% for the player's name placeholder)
      log-spam: true # Default true | logs spam punishments to the webhook
    anti-swear:
      enabled: true # Default true | Enables/disables the entire anti-swear
      low-score: 0 # Default 0 | How much score should you gain for not attempting a bypass
      medium-low-score: 0  # Default 0 | How much score should you gain for "bad "bypass attempt
      medium-score: 1 # Default 1 | How much score should you gain for "ok" bypass attempt
      medium-high-score: 3 # Default 3 | How much score should you gain for "good" bypass attempt
      high-score: 5 # Default 5 | How much score should be gained for "extreme" attempt to bypass
      punish-score: 20 # Default 20 | how much score is required to get punished
      slur-insta-punish: true # Default true | Should players get insta punished for any words on the "slurs" list?
      punish-command: "mute %player% 15m Please refrain from excessive use of profanity!"
      slur-command: "mute %player% 1h Discriminatory speech is not tolerated on this server!"
      log-swear: true # Default true | Logs swear punishments to the webhook
      whitelisted: # List known false positives here
        - glass
      blacklisted: # list all the swears you wish to blacklist here
        - ass
      slurs: # List slurs here that you wish to insta-punish for attempting
        - nigg
      leet-patterns:
        '0': o
        '1': i
        '3': e
        '4': a


