# Sentinel 0.1.8
# ____                   __                        ___
#/\  _`\                /\ \__  __                /\_ \
#\ \,\L\_\     __    ___\ \ ,_\/\_\    ___      __\//\ \
# \/_\__ \   /'__`\/' _ `\ \ \/\/\ \ /' _ `\  /'__`\\ \ \
#   /\ \L\ \/\  __//\ \/\ \ \ \_\ \ \/\ \/\ \/\  __/ \_\ \_
#   \ `\____\ \____\ \_\ \_\ \__\\ \_\ \_\ \_\ \____\/\____\
#    \/_____/\/____/\/_/\/_/\/__/ \/_/\/_/\/_/\/____/\/____/
#     ]======------ Configuration & Setup Guide ------=====[
#            Sentinel is inspired by WickBot.com
#        Be sure to check out their amazing discord bot!
#              If you need help, join the discord!
#      https://discord.gg/sentinelmc v Use below if it expired
#        https://sentinelauth.000webhostapp.com/discord.html
#
config:
  plugin:
    key: "beta" # Put your license key here. If you do not have  one, join the discord to verify your purchase
    # --------------------------------
    # Anti-Nuke Setup (Do this first)
    # --------------------------------
    prefix: "§d§lSentinel §8» §7" # Prefix of the plugin. Line below is the discord webhook for logs to be sent to
    webhook: "https://discord.com/api/webhooks/id/token"
    trusted: # List the UUIDs of players who are trusted, will bypass the plugin and be immune to logs and are able to re-op themeselves, as well as whitelist command blocks
      - "049460f7-21cb-42f5-8059-d42752bf406f" # obvWolf
    block-specific: true # Defaulted true | Weather or not to block ALL plugin specific commands from non-trusted members (EX: minecraft:execute) these will not be logged.
    prevent-nbt: true # Defaulted true | Should NBT items be blocked from the creative hotbar
    prevent-cmdblock-place: true # Defaulted true | Should Placing a command block get blocked
    prevent-cmdblock-use: true # Defaulted true | Should using a command block get blocked
    prevent-cmdblock-change: true # Defaulted true | Should changing a command block get blocked
    prevent-cmdcart-place: true # Defaulted true | Should placing a command cart get blocked
    prevent-cmdcart-use: true # Defaulted true | Should using a command cart get blocked
    cmdblock-op-check: true # Defaulted true | Will check if a player is op'd before preforming actions against command blocks (To prevent spam from non oped users attempting command blocks, which they cant by default)
    dangerous: # These commands can only be run by "trusted" users
      - "op"
      - "deop"
      - "stop"
      - "restart"
      - "execute" # Could run commands as a trusted player
      - "sudo" # same as above
      - "esudo" # WATCH OUT FOR ESSENTIALS ALIASES !!!
      - "fill" # Most client side nukers use it
      - "setblock" # could setblock a command block with anything
      - "data" # Could modify a command block to whatever they wanted
      - "whitelist" # Could add other players to the whitelist
    log-dangerous: true # Default true | Weather or not to log to discord when a dangerous command is executed
    log-cmdblocks: true # Defaulted true | Log attempts of command-block place-ery in discord
    log-nbt: true # Defaulted true | Should items and their NBT's be logged to discord
    log-specific: false # Default false | Weather or not to log to discord when a plugin specific command is executed
    logged: # Commands that will always be logged to discord when executed.
      - "give"
      - "item"
    deop: true # Defaulted true | This will remove an untrusted player's operator permissions whenever they attempt dangerous actions
    nbt-punish: false # Defaulted false | This will punish a player when they attempt to use an NBT item
    cmdblock-punish: false # Defaulted false | This will punish a player when they attempt to use a command block
    command-punish: false # Defaulted false | This will ban punish player when they attempt to use a dangerous command
    specific-punish: false # Defaulted false | This will punish a player when they run a specific command (Not recomended)
    punish-commands: # Commands to run when a dangerous action is to be punished. Use %player% for the punished player's name
      - "smite %player%"
      - "ban %player% ]=- Sentinel -=[ You have been banned for attempting a dangerous action. If you believe this to be a mistake, please contact the server owner."
    reop-command: false # Defaulted false | This enables the command allowing trusted players to op themselves if they get deoped.
  nbt:
    allow-name: true # Defaulted to true, weather or not to allow all item names durring creative inv event
    allow-lore: true # Defaulted to true, weather or not to allow all item lore during creative inv event
    allow-attributes: false # defaulted to false, weather or not to allow item attributes in a creative inv event

    # Enchants
    global-max-enchant: 5 # Defaulted to 5, if any enchantment is above this, it will get deleted. Set to 0 to disable all enchants from creative inv
    # It is recommended to keep the ones defaulted to 1 at 1, as this will keep people who spam 32k onto every enchant will get caught

    # All items
    max-mending: 1 # Defaulted to 1
    max-unbreaking: 3 # Defaulted to 3
    max-vanishing: 1 # Defaulted to 1

    # ARMOR
    max-aqua-affinity: 1 # Defaulted to 1
    max-blast-protection: 4 # Defaulted to 4
    max-curse-of-binding: 1 # Defaulted to 1
    max-depth-strider: 3 # Defaulted to 3
    max-feather-falling: 4 # Defaulted to 4
    max-fire-protection: 4 # Defaulted to 4
    max-frost-walker: 2 # Defaulted to 2
    max-projectile-protection: 4 # Defaulted to 4
    max-protection: 4 # Defaulted to 4
    max-respiration: 3 # Defaulted to 3
    max-soul-speed: 3 # Defaulted to 3
    max-thorns: 3 # Defaulted to 3
    max-swift-sneak: 3 # Defaulted to 3

    # MELEE WEAPONS
    max-bane-of-arthropods: 5 # Defaulted to 5
    max-efficiency: 5 # Defaulted to 5
    max-fire-aspect: 2 # Defaulted to 2
    max-looting: 3 # Defaulted to 3
    max-impaling: 5 # Defaulted to 5
    max-knockback: 2 # Defaulted to 2
    max-sharpness: 5 # Defaulted to 5
    max-smite: 5 # Defaulted to 5
    max-sweeping-edge: 3 # Defaulted to 3

    # RANGED WEAPONS
    max-channeling: 1 # Defaulted to 1
    max-flame: 1 # Defaulted to 1
    max-infinity: 1 # Defaulted to 1
    max-loyalty: 3 # Defaulted to 3
    max-riptide: 3 # Defaulted to 3
    max-multishot: 1 # Defaulted to 1
    max-piercing: 4 # Defaulted to 4
    max-power: 5 # Defaulted to 5
    max-punch: 2 # Defaulted to 2
    max-quick-charge: 3 # Defaulted to 3

    # TOOLS
    max-fortune: 3 # Defaulted to 3
    max-luck-of-the-sea: 3 # Defaulted to 3
    max-lure: 3 # Defaulted to 3
    max-silk-touch: 1 # Defaulted to 1

    # -------------------------------
    # Chat Filter Setup & AntiSpam
    # -------------------------------
  chat:
    anti-unicode: true # Default true | Prevents all non A-Z 0-9 + specials from being sent in chat
    anti-spam:
      # AntiSpam Heat system
      enabled: true # Default true | Enables/disables the entire anti-spam
      default-gain: 1 # Default 1 | Heat gained as base for every message
      low-gain: 2 # Default 2 | Heat gained when message is >25% similar
      medium-gain: 4 # Default 4 | Heat gained when message is >50% similar
      high-gain: 6 # Default 6 | Heat gained for >90% similarity
      heat-decay: 1 # Default 1 | Heat lost every second
      block-heat: 10 # Default 10 | The heat required to block the message
      punish-heat: 25 # Default 25 | The heat required to punish the player
      clear-chat: true # Default true | will run the clear chat command before a spam punishment
      chat-clear-command: "cc" # Default cc | Command for if "clear-chat" is enabled
      punish-command: "mute %player% 1m Please refrain from spamming!" # (Use %player% for the player's name placeholder)
      log-spam: true # Default true | logs spam punishments to the webhook
    anti-swear:
      enabled: true # Default true | Enables/disables the entire anti-swear
      low-score: 0 # Default 0 | How much score should you gain for not attempting a bypass
      medium-low-score: 1 # Default 1 | How much score should you gain for "bad "bypass attempt
      medium-score: 3 # Default 3 | How much score should you gain for "ok" bypass attempt
      medium-high-score: 5 # Default 5 | How much score should you gain for "good" bypass attempt
      high-score: 7 # Default 7 | How much score should be gained for "extreme" attempt to bypass
      score-decay: 3 # Default 3 | Rate at which score is lost every minute
      punish-score: 20 # Default 20 | how much score is required to get punished
      strict-insta-punish: true # Default true | Should players get insta punished for any words on the "strict" list?
      punish-command: "mute %player% 15m Do not attempt to bypass the Profanity Filter"
      strict-command: "mute %player% 1h Discriminatory speech is not tolerated on this server!"
      log-swear: true # Default true | Logs swear punishments to the webhook
      false-positives: # Words that will falsly flag the anti-swear
        - but then
        - was scamming
        - an alt
        - can also
        - analysis
        - analytics
        - arsenal
        - assassin
        - as saying
        - assert
        - assign
        - assimil
        - assist
        - associat
        - assum
        - assur
        - basement
        - bass
        - cass
        - butter
        - canvass
        - cocktail
        - cumber
        - document
        - evaluate
        - exclusive
        - expensive
        - explain
        - expression
        - grape
        - grass
        - harass
        - hotwater
        - identit
        - kassa
        - kassi
        - lass
        - leafage
        - libshitz
        - magnacumlaude
        - mass
        - mocha
        - pass
        - phoebe
        - phoenix
        - push it
        - sassy
        - saturday
        - scrap
        - serfage
        - sexist
        - shoe
        - stitch
        - therapist
      blacklisted: # Swears to check for
        - anal
        - anus
        - arse
        - ass
        - ballsack
        - balls
        - bastard
        - bitch
        - btch
        - biatch
        - blowjob
        - bollock
        - bollok
        - boner
        - boob
        - bugger
        - butt
        - choad
        - clitoris
        - cock
        - coon
        - crap
        - cum
        - cunt
        - dick
        - dildo
        - douchebag
        - dyke
        - feck
        - fellate
        - fellatio
        - felching
        - fuck
        - fudgepacker
        - flange
        - gtfo
        - hoe
        - horny
        - incest
        - jerk
        - jizz
        - labia
        - masturb
        - muff
        - nazi
        - nipple
        - nips
        - nude
        - pedophile
        - penis
        - piss
        - poop
        - porn
        - prick
        - prostit
        - pube
        - pussie
        - pussy
        - queer
        - rape
        - rapist
        - retard
        - rimjob
        - scrotum
        - sex
        - shit
        - slut
        - spunk
        - stfu
        - suckmy
        - tits
        - tittie
        - titty
        - turd
        - twat
        - vagina
        - wank
        - whore
      strict: # Very bad words to insta-punish for
        - nigg
        - niger
        - nlgg
        - nlger
        - njgg
        - tranny
        - fag
        - beaner
      leet-patterns: # Replacement patterns for "l33t" strings
        '0': o
        '1': i
        '3': e
        '4': a
        '5': s
        '6': g
        '7': l
        $: s
        '!': i
        '|': i
        +: t
        '#': h
        '@': a
        <: c
        V: u
        v: u


