name: Sentinel
version: '${version}'
main: io.github.thetrouper.sentinel.Sentinel
api-version: 1.19
authors: [ TheTrouper ]
description: Detect Block and Ban players who attempt to grief your server.
website: https://thetrouper.github.io/
permissions:
  sentinel.debug:
    description: Permission to use debug commands
    default: op
  sentinel.staff:
    description: Receive anti-swear and anti-spam warnings
    default: op
  sentinel.chat.antiswear.flags:
    description: See antiSwear flags
    default: op
  sentinel.chat.antiswear.bypass:
    description: Bypass the antiSwear
    default: op
  sentinel.chat.antispam.flags:
    description: See antispam flags
    default: op
  sentinel.chat.antispam.bypass:
    description: Bypass the antispam
    default: op
  sentinel.chat.*:
    description: bypass all chat rules and see all flags
    default: op
    children:
      sentinel.chat.antiswear.flags: true
      sentinel.chat.antiswear.bypass: true
      sentinel.chat.antispam.flags: true
      sentinel.chat.antispam.bypass: true
commands:
  sentinel:
    description: An info command.
    usage: /sentinel
    permission: sentinel.info
    permission-message: You do not have permission!
  reop:
    description: Allows trusted players to elevate their permissions
    usage: /reop
