name: SentinelAntiNuke
version: '${version}'
main: me.trouper.sentinel.Sentinel
api-version: 1.20
authors: [ TheTrouper ]
description: Detect, Block, and Ban players who attempt to grief your server.
website: https://thetrouper.github.io/
softdepend: [ ProtocolLib ]
load: STARTUP
permissions:
  sentinel.message:
    description: Access to the direct messages
    default: op
  sentinel.reply:
    description: Reply commands
  sentinel.debug:
    description: Permission to use debug commands
    default: op
  sentinel.staff:
    description: Receive anti-swear and anti-spam warnings
    default: op
  sentinel.chat.antiswear.flags:
    description: See antiSwear flags
    default: op
  sentinel.chat.antiswear.bypass:
    description: Bypass the antiSwear
    default: op
  sentinel.chat.antiswear.edit:
    description: Add a false positive to the config
    default: op
  sentinel.chat.antispam.flags:
    description: See antispam flags
    default: op
  sentinel.chat.antispam.bypass:
    description: Bypass the antispam
    default: op
  sentinel.chat.*:
    description: bypass all chat rules and see all flags
    default: op
    children:
      sentinel.chat.antiswear.flags: true
      sentinel.chat.antiswear.bypass: true
      sentinel.chat.antispam.flags: true
      sentinel.chat.antispam.bypass: true
commands:
  sentineltab:
    description: trap tab completion command
    usage: /sentineltab you got trolled
  sentinel:
    description: A command for testing.
    usage: /sentinel
    permission: sentinel.info
    permission-message: You do not have permission!
  reop:
    description: Allows trusted players to elevate their permissions
    usage: /reop
  socialspy:
    permission: sentinel.spy
    usage: /socialspy
    permission-message: You do not have permission to use this command!
    description: View direct messages sent between players
    aliases:
      - spy
      - sspy
  msg:
    permission: sentinel.message
    usage: /msg <player> [<message>]
    permission-message: You do not have permission to message through sentinel!
    description: Send messages directly to players
    aliases:
      - message
      - etell
      - tell
      - t
      - ewhisper
      - whisper
      - w
      - privatemessage
      - pm
      - m
      - directmessage
      - dm
      - sentinelmessage
      - sm
      - stell
      - smsg
  reply:
    description: Reply to the last person messaging you
    usage: /r [<message>]
    permission: sentinel.reply
    permission-message: You do not have permission to reply through sentinel!
    aliases:
      - r
      - er
      - rply
      - ereply
      - sr
      - sreply
      - sentinelreply
  sentinelcallback:
    description: Callback for chat click events
    usage: /sentinelcallback
    permission: sentinel.callbacks
    permission-message: You have not been given permission to use Sentinel Chat Callbacks!