name: Sentinel
version: '${version}'
main: io.github.thetrouper.sentinel.Sentinel
api-version: 1.17
authors: [ TheTrouper ]
description: Detect Block and Ban players who attempt to grief your server.
website: https://thetrouper.github.io/
permissions:
  sentinel.info:
    description: Permission to view sentinel info
    default: op
commands:
  sentinel:
    description: An info command.
    usage: /sentinel
    permission: sentinel.info
    permission-message: You do not have permission!
  reop:
    description: Allows trusted players to elevate their permissions
    usage: /reop
